export const cakeList = [
  {
    id: 0,
    name: "Cranberry Lemon",
    price: 10,
    imagePath300: "images/CranberryLemon300.jpg",
    imagePath600: "images/CranberryLemon600.jpg",
    garnishes: "Sugared cranberries: 1 cup normal cake size",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "New",
      couponLocation: "",
      couponID: "",
      couponUnit: "",
      couponQuantity: "",
      couponExpiry: "",
    },
    description:
      "This moist rum cake is loaded with fresh cranberries along with fresh squeezed lemon juice and zest. It’s a great dessert for the entire fall and winter season.",
  },
  {
    id: 1,
    name: "Original",
    price: 10,
    imagePath300: "images/Original300.jpg",
    imagePath600: "images/Original600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "8116491632888194521",
      couponUnit: "Percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Made from scratch with premium ingredients, this moist delicious vanilla rum cake is a top shelf original.",
  },
  {
    id: 2,
    name: "Dark Chocolate",
    price: 10,
    imagePath300: "images/DarkChocolate300.jpg",
    imagePath600: "images/DarkChocolate600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "4121272542865338333",
      couponUnit: "Percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Made from scratch with fresh ingredients and premium dark chocolate with a buttery and real rum sauce.",
  },
  {
    id: 3,
    name: "Bananas Foster",
    price: 10,
    imagePath300: "images/BananasFoster300.jpg",
    imagePath600: "images/BananasFoster600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "3359501940720522637",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Caramelized bananas top this banana rum cake producing a smooth and sweet tasty treat.",
  },
  {
    id: 4,
    name: "Ginger Lime",
    price: 10,
    imagePath300: "images/GingerLime300.jpg",
    imagePath600: "images/GingerLime600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "5875205429321172897",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Crystallized ginger bits along with lime zest and juice makes this a moist and zingy cake that will test your taste buds with tingle and delight.",
  },
  {
    id: 5,
    name: "Coconut",
    price: 10,
    imagePath300: "images/Coconut300.jpg",
    imagePath600: "images/Coconut600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "7752985497517278006",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "If you like coconut, try coconut soaked in rum.  There are so many coconut flakes in this moist coconut rum cake you will think you are on a beach with a delicious cocktail.",
  },
  {
    id: 6,
    name: "Spiced Apple",
    price: 10,
    imagePath300: "images/SpicedApple300.jpg",
    imagePath600: "images/SpicedApple600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "1178969077236784993",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Loads of delicious spiced apple pieces are swirled throughout this cake.  You will yield to the eye-closing deliciousness.",
  },
  {
    id: 7,
    name: "Cinnamon Bun",
    price: 10,
    imagePath300: "images/CinnamonBun300.jpg",
    imagePath600: "images/CinnamonBun600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "3376166476843835844",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "All the cinnamon bun flavors of cream cheese and layers of cinnamon sugar swirls.  Just close your eyes and shiver with delight...",
  },
  {
    id: 8,
    name: "Apple Cinnamon",
    price: 10,
    imagePath300: "images/AppleCinnamon300.jpg",
    imagePath600: "images/AppleCinnamon600.jpg",
    garnishes: "",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "Coupon",
      couponLocation: "facebook",
      couponID: "8282539994401140249",
      couponUnit: "percent",
      couponQuantity: "15",
      couponExpiry: "2019-10-10",
    },
    description:
      "Like the Spiced Apple and Cinnamon Bun?  Try this with your coffee – just once.  We dare you!  You’ll be hooked.",
  },
  {
    id: 9,
    name: "Butter Maple Pecan",
    price: 10,
    imagePath300: "images/ButterMaplePecan300.jpg",
    imagePath600: "images/ButterMaplePecan600.jpg",
    garnishes: "Candied pecans: 1 cup normal cake size",
    sizes: ["regular", "mini"],
    coupon: {
      couponType: "New",
      couponLocation: "",
      couponID: "",
      couponUnit: "",
      couponQuantity: "",
      couponExpiry: "",
    },
    description:
      "Delicious maple syrup along with crushed pecans and rum, make this a divine rum cake for any occasions this fall.",
  },
];
